# Generated by Django 6.0.6 on 2026-06-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_product_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_store', to='stores.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_store', to='stores.store')),
            ],
        ),
    ]
