# Generated by Django 6.0.6 on 2026-06-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
