# Generated by Django 6.0.6 on 2026-06-18 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('offered_price', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('buyer_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_store', to='stores.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
                ('seller_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_store', to='stores.store')),
            ],
        ),
    ]
