# Generated by Django 6.0.6 on 2026-06-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
