# Generated by Django 6.0.6 on 2026-06-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
