# Generated by Django 6.0.6 on 2026-06-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='buyer_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_offers', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='seller_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_offers', to='stores.store'),
        ),
    ]
