# Generated by Django 6.0.6 on 2026-06-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_offer_buyer_store_alter_offer_seller_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
