# Generated by Django 6.0.6 on 2026-06-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
