# Generated by Django 6.0.6 on 2026-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
