# Generated by Django 6.0.6 on 2026-06-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_offer_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
